server:
  port: 9090

spring:
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
          filters:
            - RewritePath=/api/customers/(?<segment>.*), /customers/${segment}

        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/api/billing/**
          filters:
            - RewritePath=/api/billing/(?<segment>.*), /billing/${segment}
