resilience4j:
  circuitbreaker:
    instances:
      paymentApi:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers,circuitbreakerevents
