server:
  port: 9090

spring:
  application:
    name: edge-gateway
  cloud:
    gateway:
      routes:
        - id: example-service-route
          uri: lb://example-service
          predicates:
            - Path=/loadbalanced/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: exampleCircuitBreaker
                fallbackUri: forward:/fallback/example

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      exampleCircuitBreaker:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
